### ISSUE TITLE
LCP EPUB: Can't select text to either share or highlight with DRM protected books

### ISSUE THREAD

**Issue by A-Fawzyy** [readium/kotlin-toolkit#299]
### What happened?
The text selection popup in the reader screen doesn't show when testing with a protected / encrypted book.

### Expected behavior
The selection popup should show.

### How to reproduce?

1. Open a protected / encrypted EPUB
2. Long press any text
3. Check if the selection popup shows

### Environment

* Readium version: 2.2.1

#### Development environment

* OS: macOS Ventura 13.0
* IDE:  Android Studio Dolphin | 2021.3.1 Patch 1

#### Testing device

* Android version: 11
* Model:  Pixel 2 API 31
* Is it an emulator? Yes

### Additional context

* Are you willing to fix the problem and contribute a pull request? Yes or No Yes

**Comment by mickael-menu** [comment]
This is by design, as long as [we don't support Copy rights with LCP in the Kotlin toolkit](https://github.com/readium/kotlin-toolkit/issues/223), the selection is disabled to prevent users from copying the book content.

You could fork and remove the protection here:

https://github.com/readium/kotlin-toolkit/blob/30c729636be4057a9144f2dd6ee3428309088fe1/readium/navigator/src/main/java/org/readium/r2/navigator/epub/HtmlInjector.kt#L35

and there:

https://github.com/readium/kotlin-toolkit/blob/540c80fc1c57f04d09db45764f103724177aedf9/readium/streamer/src/main/java/org/readium/r2/streamer/fetcher/HtmlInjector.kt#L115

**but only** if you remove the Copy and Share selection menu items in your app, when the publication is protected. Otherwise, you will void the EDRLab certification for your app.
